name: x86-64
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
   build:
    runs-on: ubuntu-latest
    env: 
      DEVICE: x86-64
      UPLOAD_OUTPUT: true
      RELEASE: false
    steps:
    - name: build
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        mkdir bin
        chmod 777 bin
        docker run --rm -v "$(pwd)"/bin/:/builder/bin openwrt/imagebuilder:x86-64-23.05.0 make image ROOTFS_PARTSIZE="512" PACKAGES="kmod-igbvf -kmod-amazon-ena -kmod-amd-xgbe -kmod-bnx2 -kmod-igc -kmod-ixgbe -kmod-r8169 -kmod-tg3"
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    - name: upload
      uses: actions/upload-artifact@master
      if: env.UPLOAD_OUTPUT == 'true' && !cancelled()
      with:
        name: ${{ env.DEVICE }}--${{ env.FILE_DATE }}
        path: bin/
    - name: Release
      uses: ncipollo/release-action@v1
      if: env.RELEASE == 'true' && !cancelled()
      with:
        tag: "${{ env.DEVICE }}--${{ env.FILE_DATE }}"
        artifacts: bin/
        body: |
          # 未测试×
